version: 1
disable_existing_loggers: false

formatters:
  # Simple format for Cloud Run (GCP handles timestamps)
  simple:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

  # JSON format for structured logging (best for GCP)
  json:
    (): "pythonjsonlogger.jsonlogger.JsonFormatter"
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

handlers:
  # Console handler - this is what Cloud Run captures
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

loggers:
  # Your app logger
  src:
    level: INFO
    handlers: [console]
    propagate: false

  # Reduce noise from external libraries
  urllib3:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
